name: Build and deploy Python app to Azure Web App - AI-Policy-Reader

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*" ".git/*" ".github/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F5C9E61ED8594C58A36016E4157B8AB3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FF78FBEBF99144D3814805CF42777CAE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0F9B7B0930F64E17A777E5CA01CE15C2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ai-policy-reader'
          package: release.zip